package com.sathira.miimoneypal.rest.transactions.post;

import com.sathira.miimoneypal.jooq.tables.records.TransactionsRecord;
import com.sathira.miimoneypal.records.transaction.Transaction;
import com.sathira.miimoneypal.records.transaction.TransactionType;
import lombok.RequiredArgsConstructor;
import org.jooq.DSLContext;
import org.springframework.stereotype.Repository;

import static com.sathira.miimoneypal.jooq.tables.Transactions.TRANSACTIONS;

/**
 * jOOQ implementation for creating transactions.
 * Handles database insertion with type-safe SQL.
 */
@Repository
@RequiredArgsConstructor
public class PostTransactionRepository implements PostTransactionDataAccess {

    private final DSLContext dsl;

    @Override
    public Transaction create(Transaction transaction) {
        TransactionsRecord record = dsl.newRecord(TRANSACTIONS);

        // Set all fields (id, createdAt, updatedAt will be generated by database)
        record.setUserId(transaction.userId());
        record.setType(transaction.type().name());
        record.setAmount(transaction.amount());
        record.setTransactionDate(transaction.transactionDate());
        record.setCategoryId(transaction.categoryId());
        record.setBucketId(transaction.bucketId());
        record.setNote(transaction.note());

        // Insert and return generated values
        record.store();

        // Convert back to domain record with generated values
        return toDomainRecord(record);
    }

    /**
     * Convert jOOQ TransactionsRecord to domain Transaction record.
     */
    private Transaction toDomainRecord(TransactionsRecord record) {
        return Transaction.builder()
                .id(record.getId())
                .userId(record.getUserId())
                .type(TransactionType.valueOf(record.getType()))
                .amount(record.getAmount())
                .transactionDate(record.getTransactionDate())
                .categoryId(record.getCategoryId())
                .bucketId(record.getBucketId())
                .note(record.getNote())
                .createdAt(record.getCreatedAt())
                .updatedAt(record.getUpdatedAt())
                .build();
    }
}
